/**
 * Resolves every recipe for the professions in PROFESSION_SKILL_LINES —
 * plus whatever's actually been imported (covers Enchanting-style
 * professions where an addon can hand us a spellId directly, and anything
 * outside PROFESSION_SKILL_LINES) — against Wowhead, and updates the
 * checked-in catalog at src/data/wowhead/tbc/recipes.ts. This makes the
 * catalog a complete reference, browsable before anyone's imported a
 * character that knows a given recipe. Run with:
 *
 *   pnpm wowhead:sync
 *
 * Safe to re-run any time — already-known names (recipes and reagents
 * alike) are skipped, so it only fetches what's new.
 *
 * Reagents/description are parsed from the tooltip HTML Wowhead returns.
 * That HTML only carries reagent info for spell tooltips (enchants cast as
 * a spell show "Reagents:" right there) — plain crafted items (Cooking,
 * Engineering, ...) don't expose their reagents on their own item tooltip.
 * Run `pnpm resolve-spell-ids` first to fill in Recipe.spellId for imported
 * recipes in professions outside PROFESSION_SKILL_LINES.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { PrismaClient } from "@guildthing/db";
import { tbcRecipes } from "../src/tbc/recipes";
import type { WowheadEntry, WowheadReagent } from "../src/types";
import {
  fetchProfessionSpells,
  PROFESSION_SKILL_LINES,
} from "../src/profession-catalog";

const EXPANSION = "tbc";
const RECIPES_FILE = fileURLToPath(
  new URL("../src/tbc/recipes.ts", import.meta.url),
);
const PROFESSIONS_FILE = fileURLToPath(
  new URL("../src/tbc/professions.ts", import.meta.url),
);
const REQUEST_DELAY_MS = 200;

const db = new PrismaClient();

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

interface TooltipResponse {
  name: string;
  icon: string;
  quality?: number;
  tooltip?: string;
}

async function fetchTooltip(
  kind: "item" | "spell",
  id: number,
): Promise<TooltipResponse> {
  const res = await fetch(
    `https://nether.wowhead.com/${EXPANSION}/tooltip/${kind}/${id}`,
  );
  if (!res.ok) {
    throw new Error(`Wowhead tooltip ${kind}/${id} failed: ${res.status}`);
  }
  return (await res.json()) as TooltipResponse;
}

function decodeEntities(s: string): string {
  return s
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, " ")
    .trim();
}

function parseDescription(tooltipHtml: string): string | undefined {
  const match = /<div class="q">([\s\S]*?)<\/div>/.exec(tooltipHtml);
  if (!match?.[1]) return undefined;
  return decodeEntities(match[1].replace(/<[^>]+>/g, ""));
}

interface ParsedReagent extends WowheadReagent {
  itemId: number;
}

function parseReagents(tooltipHtml: string): ParsedReagent[] | undefined {
  const block = /Reagents:<br \/><div class="indent q1">([\s\S]*?)<\/div>/.exec(
    tooltipHtml,
  )?.[1];
  if (!block) return undefined;

  const reagents: ParsedReagent[] = [];
  const itemRe = /<a href="\/tbc\/item=(\d+)\/[^"]*">([^<]+)<\/a>(?:&nbsp;\((\d+)\))?/g;
  let m;
  while ((m = itemRe.exec(block))) {
    const [, itemId, name, qty] = m;
    reagents.push({
      itemId: Number(itemId),
      name: decodeEntities(name!),
      quantity: qty ? Number(qty) : 1,
    });
  }
  return reagents.length > 0 ? reagents : undefined;
}

function writeRecipesFile(entries: Record<string, WowheadEntry>) {
  const sortedKeys = Object.keys(entries).sort((a, b) => a.localeCompare(b));
  const body = sortedKeys
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(entries[key])},`)
    .join("\n");

  const content = `import type { WowheadEntry } from "../types";

// Generated by \`pnpm wowhead:sync\` — do not hand-edit entries, re-run the
// script instead. Keys are recipe/reagent names as they appear in imported
// character data or in other entries' reagent lists.
export const tbcRecipes: Record<string, WowheadEntry> = {
${body}
};
`;

  writeFileSync(RECIPES_FILE, content);
}

function writeProfessionsFile(professionNames: Record<string, string[]>) {
  const sortedProfessions = Object.keys(professionNames).sort((a, b) =>
    a.localeCompare(b),
  );
  const body = sortedProfessions
    .map((profession) => {
      const names = [...professionNames[profession]!].sort((a, b) =>
        a.localeCompare(b),
      );
      return `  ${JSON.stringify(profession)}: ${JSON.stringify(names)},`;
    })
    .join("\n");

  const content = `// Generated by \`pnpm wowhead:sync\` — do not hand-edit, re-run the
// script instead. Maps each profession to every recipe name tbcdb lists for
// it (including specializations and rank-up markers), independent of
// whether anyone's imported a character that knows it. Used to group the
// admin raw-catalog view into per-profession categories.
export const tbcProfessionRecipes: Record<string, string[]> = {
${body}
};
`;

  writeFileSync(PROFESSIONS_FILE, content);
}

async function main() {
  const recipes = await db.recipe.findMany({
    select: { name: true, itemId: true, spellId: true },
  });

  const byName = new Map<string, { itemId: number | null; spellId: number | null }>();
  for (const r of recipes) {
    if (!byName.has(r.name)) {
      byName.set(r.name, { itemId: r.itemId, spellId: r.spellId });
    }
  }

  // Seed every recipe that exists for these professions, not just ones
  // someone's imported — makes the catalog a complete, browsable reference.
  // Also records each profession's full name list, for grouping the admin
  // raw-catalog view into per-profession categories.
  const professionNames: Record<string, string[]> = {};
  for (const [professionName, skillLineQuery] of Object.entries(
    PROFESSION_SKILL_LINES,
  )) {
    try {
      const professionRecipes = await fetchProfessionSpells(skillLineQuery);
      professionNames[professionName] = professionRecipes.map((r) => r.name);
      for (const r of professionRecipes) {
        if (!byName.has(r.name)) {
          byName.set(r.name, { itemId: null, spellId: r.spellId });
        }
      }
    } catch (err) {
      console.error(
        `[wowhead-sync] failed to fetch full ${professionName} catalog:`,
        err,
      );
    }
    await sleep(REQUEST_DELAY_MS);
  }
  writeProfessionsFile(professionNames);

  const entries: Record<string, WowheadEntry> = { ...tbcRecipes };
  let added = 0;
  let alreadyKnown = 0;
  let upgraded = 0;
  const unresolved: string[] = [];

  // Recipes synced back when only itemId was known (e.g. Cooking/Engineering
  // before resolve-spell-ids ran) got a bare item entry with no
  // reagents/description. Now that spellId is available, drop those stale
  // entries so the loop below re-resolves them via the spell tooltip.
  for (const [name, ids] of byName) {
    if (ids.spellId != null && entries[name]?.kind === "item") {
      delete entries[name];
      upgraded++;
    }
  }

  // Fetches+caches a plain item entry (used for reagent materials, which
  // never carry their own reagents/description).
  async function ensureItemEntry(name: string, itemId: number) {
    if (entries[name]) return;
    const tooltip = await fetchTooltip("item", itemId);
    entries[name] = {
      kind: "item",
      id: itemId,
      name: tooltip.name,
      icon: tooltip.icon,
      quality: tooltip.quality,
    };
    added++;
    await sleep(REQUEST_DELAY_MS);
  }

  for (const [name, ids] of byName) {
    if (entries[name]) {
      alreadyKnown++;
      continue;
    }

    const kind = ids.spellId != null ? "spell" : ids.itemId != null ? "item" : null;
    const id = ids.spellId ?? ids.itemId;

    if (!kind || id == null) {
      unresolved.push(name);
      continue;
    }

    try {
      const tooltip = await fetchTooltip(kind, id);
      const reagents = tooltip.tooltip ? parseReagents(tooltip.tooltip) : undefined;

      entries[name] = {
        kind,
        id,
        name: tooltip.name,
        icon: tooltip.icon,
        quality: tooltip.quality,
        description: tooltip.tooltip ? parseDescription(tooltip.tooltip) : undefined,
        reagents: reagents?.map(({ name: rName, quantity }) => ({ name: rName, quantity })),
      };
      added++;

      await sleep(REQUEST_DELAY_MS);

      for (const reagent of reagents ?? []) {
        await ensureItemEntry(reagent.name, reagent.itemId);
      }
    } catch (err) {
      console.error(`[wowhead-sync] failed to resolve "${name}" (${kind} ${id}):`, err);
      unresolved.push(name);
      await sleep(REQUEST_DELAY_MS);
    }
  }

  // --- itemId backfill ---
  // A reagent that's itself a crafted item (kind:"spell") never had its own
  // item-form itemID captured anywhere — parseReagents() extracts it from
  // the referencing tooltip's item link, but the add/upgrade loop above
  // only keeps {name, quantity} on the reagent list, discarding it. This
  // pass fills WowheadEntry.itemId in after the fact, for every entry it
  // can find as someone else's reagent. Idempotent and additive-only: once
  // an entry's itemId is set it's never a "gap" again, so a future run only
  // re-fetches recipes that are new or still genuinely missing data.
  let itemIdFilled = 0;

  // kind:"item" entries already know their own itemID as `id` — free, no
  // fetch needed.
  for (const entry of Object.values(entries)) {
    if (entry.kind === "item" && entry.itemId == null) {
      entry.itemId = entry.id;
      itemIdFilled++;
    }
  }

  // kind:"spell" entries whose item-form itemID is still missing: only
  // discoverable by re-parsing the tooltip of a recipe that uses them as a
  // reagent, since that's the only place the item link (and its itemID)
  // appears.
  let recipesRefetched = 0;
  for (const [name, entry] of Object.entries(entries)) {
    if (entry.kind !== "spell" || !entry.reagents) continue;
    const hasGap = entry.reagents.some((r) => {
      const target = entries[r.name];
      return target?.kind === "spell" && target.itemId == null;
    });
    if (!hasGap) continue;

    try {
      const tooltip = await fetchTooltip("spell", entry.id);
      const reagents = tooltip.tooltip ? parseReagents(tooltip.tooltip) : undefined;
      for (const r of reagents ?? []) {
        const target = entries[r.name];
        if (target && target.itemId == null) {
          target.itemId = r.itemId;
          itemIdFilled++;
        }
      }
      recipesRefetched++;
      await sleep(REQUEST_DELAY_MS);
    } catch (err) {
      console.error(`[wowhead-sync] itemId backfill failed for "${name}":`, err);
    }
  }

  const stillUnresolved = Object.values(entries).filter(
    (e) =>
      e.kind === "spell" &&
      e.reagents?.some((r) => {
        const t = entries[r.name];
        return t?.kind === "spell" && t.itemId == null;
      }),
  ).length;
  console.log(`[wowhead-sync] itemId backfill: ${itemIdFilled} entries filled, ${recipesRefetched} recipes re-fetched, ${stillUnresolved} recipes still with an unresolved reagent itemId`);

  writeRecipesFile(entries);

  console.log(`[wowhead-sync] added: ${added}, upgraded: ${upgraded}, already known: ${alreadyKnown}, unresolved: ${unresolved.length}`);
  if (unresolved.length > 0) {
    console.log("[wowhead-sync] unresolved (no id available yet):");
    for (const name of unresolved) console.log(`  - ${name}`);
  }
}

main()
  .catch((err: unknown) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
