// Generated by `pnpm wowhead:sync` — do not hand-edit, re-run the
// script instead. Maps each profession to every recipe name tbcdb lists for
// it (including specializations and rank-up markers), independent of
// whether anyone's imported a character that knows it. Used to group the
// admin raw-catalog view into per-profession categories.
export const tbcProfessionRecipes: Record<string, string[]> = {
  "Alchemy": [],
  "Blacksmithing": [],
  "Cooking": [],
  "Enchanting": [],
  "Engineering": [],
  "Jewelcrafting": [],
  "Leatherworking": [],
  "Tailoring": [],
};
