/**
 * Generates GuildThing/Data/Recipes.lua from the catalog in
 * @guildthing/wowhead-data — the addon needs its own static copy since it
 * has to work fully offline in the WoW client (no DB, no network). Run
 * with:
 *
 *   pnpm addon:catalog
 *
 * Re-run whenever `pnpm wowhead:sync` updates the source catalog, then
 * `pnpm addon:package` to re-zip the addon with the new data.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import {
  PROFESSION_SKILL_LINES,
  tbcProfessionRecipes,
  tbcRecipes,
} from "@guildthing/wowhead-data";

const OUT_FILE = fileURLToPath(
  new URL("../GuildThing/Data/Recipes.lua", import.meta.url),
);

function luaString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

const professionNames = Object.keys(PROFESSION_SKILL_LINES);

const lines: string[] = [];
lines.push("-- Generated by `pnpm addon:catalog` — do not hand-edit, re-run instead.");
lines.push(
  "GuildThing_CatalogOrder = { " +
    professionNames.map(luaString).join(", ") +
    " }",
);
lines.push("GuildThing_Catalog = {");

for (const profession of professionNames) {
  // Same dedupe-then-resolve-then-sort as profession-recipe-browser.tsx's
  // `combined` — the raw list includes rank-up markers and duplicates.
  const names = [...new Set(tbcProfessionRecipes[profession] ?? [])].sort(
    (a, b) => a.localeCompare(b),
  );

  lines.push(`  [${luaString(profession)}] = {`);
  for (const name of names) {
    const entry = tbcRecipes[name];
    if (!entry) continue; // no catalog data to resolve this name against

    const fields = [
      `name = ${luaString(entry.name)}`,
      `kind = ${luaString(entry.kind)}`,
      `id = ${entry.id}`,
      `icon = ${luaString(entry.icon)}`,
    ];
    if (typeof entry.quality === "number") {
      fields.push(`quality = ${entry.quality}`);
    }

    lines.push(`    { ${fields.join(", ")} },`);
  }
  lines.push("  },");
}

lines.push("}");
lines.push("");

writeFileSync(OUT_FILE, lines.join("\n"));

console.log(`[export-addon-catalog] wrote ${OUT_FILE}`);
